---
abstract: 'Encrypted cookie-based session backend for Dancer'
author:
  - 'Alex Kapranoff <kappa@cpan.org>'
  - 'Alex Sukria <sukria@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Dancer::ModuleLoader: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  FindBin: 0
  HTTP::Cookies: 0
  HTTP::Date: 0
  LWP: 0
  LWP::UserAgent: 0
  List::Util: 0
  Test::Exception: 0
  Test::More: 0.96
  Test::NoWarnings: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-Cookie
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dancer::Session::Cookie:
    file: lib/Dancer/Session/Cookie.pm
    version: 0.21
requires:
  Crypt::CBC: 0
  Crypt::Rijndael: 0
  Dancer: 1.3113
  Dancer::Cookie: 0
  Dancer::Cookies: 0
  Dancer::Session::Abstract: 0
  MIME::Base64: 0
  Session::Storage::Secure: 0
  Storable: 0
  String::CRC32: 0
  Time::Duration::Parse: 0
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/dancer-session-cookie/issues
  homepage: https://metacpan.org/release/Dancer-Session-Cookie
  repository: git://github.com/dagolden/dancer-session-cookie.git
version: 0.21
x_contributors:
  - 'Michael G. Schwern <schwern@pobox.com>'
  - 'Neil Kirsopp <neil@broadbean.com>'
  - 'Nick S. Knutov <nick@knutov.com>'
