--- #YAML:1.0
name:                Dancer-Session-Cookie
version:             0.1
abstract:            Encrypted cookie-based session backend for Dancer
license:             perl
author:              
    - Alex Kapranoff <kappa@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Crypt::CBC:                    0
    Crypt::Rijndael:               0
    Dancer:                        1.13
    String::CRC32:                 0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
